FROM node:24.9.0-trixie@sha256:d77976ca59a7d6066208506456cdffa1ae9e10df29bbc822c7ee45ae27816574 AS base

FROM base AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --no-audit

COPY . .
RUN npm run build:release

FROM base

RUN groupadd appgroup && \
  useradd -g appgroup -m appuser
USER appuser

WORKDIR /app

COPY --chown=appuser:appgroup package.json package-lock.json ./
RUN npm ci --omit=dev --no-audit

COPY --from=builder --chown=appuser:appgroup /app/build ./build

ENV CONFIG_PATH=/app/conf \
  CACHE_DIR=/app/cache

HEALTHCHECK NONE

CMD ["node", "build/src/main.js", "--daemon"]
