FROM node:20.14.0-buster@sha256:d8ef9465f464015a2667c7822bbb91d29979d6446b0da032c6a671f1ed3acf24 as base

FROM base as builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --no-audit

COPY . .
RUN npm run build:release

FROM base

RUN groupadd appgroup && \
  useradd -g appgroup -m appuser
USER appuser

WORKDIR /app

COPY --chown=appuser:appgroup package.json package-lock.json ./
RUN npm ci --omit=dev --no-audit

COPY --from=builder --chown=appuser:appgroup /app/build ./build

ENV CONFIG_PATH /app/conf
ENV CACHE_DIR /app/cache

HEALTHCHECK NONE

CMD ["node", "build/src/main.js", "--daemon"]
