FROM node:23.1.0-bookworm@sha256:99c5f40071f14c686b62d108a440aed65b786b8c928eb885ca16ca5685e5e33a as base

FROM base as builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --no-audit

COPY . .
RUN npm run build:release

FROM base

RUN groupadd appgroup && \
  useradd -g appgroup -m appuser
USER appuser

WORKDIR /app

COPY --chown=appuser:appgroup package.json package-lock.json ./
RUN npm ci --omit=dev --no-audit

COPY --from=builder --chown=appuser:appgroup /app/build ./build

ENV CONFIG_PATH /app/conf
ENV CACHE_DIR /app/cache

HEALTHCHECK NONE

CMD ["node", "build/src/main.js", "--daemon"]
