FROM node:22.6.0-bullseye@sha256:34376243bf21c11e843b2a0eb25b28b471cfc45ec5ad56b0968e81a9493b8ffe as base

FROM base as builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --no-audit

COPY . .
RUN npm run build:release

FROM base

RUN groupadd appgroup && \
  useradd -g appgroup -m appuser
USER appuser

WORKDIR /app

COPY --chown=appuser:appgroup package.json package-lock.json ./
RUN npm ci --omit=dev --no-audit

COPY --from=builder --chown=appuser:appgroup /app/build ./build

ENV CONFIG_PATH /app/conf
ENV CACHE_DIR /app/cache

HEALTHCHECK NONE

CMD ["node", "build/src/main.js", "--daemon"]
