FROM node:23.10.0-bullseye@sha256:fd1dd557d7db9d20a36c900df1e3b968291c1deeeb6cdbff0b2fbae1d2d76309 as base

FROM base as builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --no-audit

COPY . .
RUN npm run build:release

FROM base

RUN groupadd appgroup && \
  useradd -g appgroup -m appuser
USER appuser

WORKDIR /app

COPY --chown=appuser:appgroup package.json package-lock.json ./
RUN npm ci --omit=dev --no-audit

COPY --from=builder --chown=appuser:appgroup /app/build ./build

ENV CONFIG_PATH /app/conf
ENV CACHE_DIR /app/cache

HEALTHCHECK NONE

CMD ["node", "build/src/main.js", "--daemon"]
