FROM node:22.3.0-alpine3.20@sha256:415f3219943ef82fa45988acdaa7df05a0b52cabd3502095c59d34cbe28c1bc1 as base

FROM base as builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --no-audit

COPY . .
RUN npm run build:release

FROM base

RUN addgroup -S appgroup && \
  adduser -S appuser -G appgroup
USER appuser

WORKDIR /app

COPY --chown=appuser:appgroup package.json package-lock.json ./
RUN npm ci --omit=dev --no-audit

COPY --from=builder --chown=appuser:appgroup /app/build ./build

ENV CONFIG_PATH /app/conf
ENV CACHE_DIR /app/cache

HEALTHCHECK NONE

CMD ["node", "build/src/main.js", "--daemon"]
