FROM node:24.4.1-bullseye@sha256:2faab98961b4dc60089a930446f4cf6dde7dbe267f982b3f6b11f36265238a8f AS base

FROM base AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --no-audit

COPY . .
RUN npm run build:release

FROM base

RUN groupadd appgroup && \
  useradd -g appgroup -m appuser
USER appuser

WORKDIR /app

COPY --chown=appuser:appgroup package.json package-lock.json ./
RUN npm ci --omit=dev --no-audit

COPY --from=builder --chown=appuser:appgroup /app/build ./build

ENV CONFIG_PATH=/app/conf \
  CACHE_DIR=/app/cache

HEALTHCHECK NONE

CMD ["node", "build/src/main.js", "--daemon"]
