FROM node:24.5.0-bookworm@sha256:14fe96d5b60b7fe5ac5eeed9e5866a23412cb8503d8a2fd215f6a923cca6de58 AS base

FROM base AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --no-audit

COPY . .
RUN npm run build:release

FROM base

RUN groupadd appgroup && \
  useradd -g appgroup -m appuser
USER appuser

WORKDIR /app

COPY --chown=appuser:appgroup package.json package-lock.json ./
RUN npm ci --omit=dev --no-audit

COPY --from=builder --chown=appuser:appgroup /app/build ./build

ENV CONFIG_PATH=/app/conf \
  CACHE_DIR=/app/cache

HEALTHCHECK NONE

CMD ["node", "build/src/main.js", "--daemon"]
