name: TODO Database

target:
  - <32-digit-database-id>

on: [create, update]

jobs:
  set_todo:
    name: set_todo
    if: is_empty(property('Status'))
    steps:
      - name: Set status property
        run: set_property('Status', 'TODO')
