name: TODO Database

target:
  - <32-digit-database-id>

on: [create, update]

jobs:
  set_todo:
    name: set_todo
    if: page.get_property('Status').is_empty()
    steps:
      - name: Set status property
        run: page.set_property('Status', 'TODO')
