name: Docker CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  alpine:
    name: Build alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Build Docker Image
        run: docker build -t nodop:alpine -f docker/Dockerfile.alpine .

  bookworm:
    name: Build bookworm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Build Docker Image
        run: docker build -t nodop:bookworm -f docker/Dockerfile.bookworm .

  bullseye:
    name: Build bullseye
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Build Docker Image
        run: docker build -t nodop:bullseye -f docker/Dockerfile.bullseye .

  buster:
    name: Build buster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Build Docker Image
        run: docker build -t nodop:buster -f docker/Dockerfile.buster .
