name: Docker CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  alpine:
    name: Build alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build Docker Image
        run: docker build -t nodop:alpine -f docker/Dockerfile.alpine .

  trixie:
    name: Build trixie
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build Docker Image
        run: docker build -t nodop:trixie -f docker/Dockerfile.trixie .

  bookworm:
    name: Build bookworm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build Docker Image
        run: docker build -t nodop:bookworm -f docker/Dockerfile.bookworm .

