name: Lint Code Base

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@56576d491db07c7236b445ab09991ca49d12b0c6 # v6.5.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_EDITORCONFIG: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
