name: Lint Code Base

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@5b638caee6ba65e25e07143887b669a1233847a0 # v6.5.1
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_EDITORCONFIG: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
