name: Releases

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        id: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Release
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ steps.release_drafter.outputs.id }},
              tag_name: '${{ github.ref_name }}',
              name: 'Release ${{ github.ref_name }}',
              draft: context.eventName != 'push'
            });

  docker:
    name: Build Docker Image
    strategy:
      matrix:
        base-image: [alpine3.22, trixie, bookworm]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up tags
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          IMAGE_NAME: harryzcy/nodop
          BASE_IMAGE: ${{ matrix.base-image }}
        with:
          script: |
            const image_name = process.env.IMAGE_NAME
            const tag_name = context.eventName == 'push' ? process.env.GITHUB_REF_NAME : 'v0.0.0'
            const base_image = process.env.BASE_IMAGE
            const [major, minor, patch] = tag_name.slice(1).split('.')
            const version_tags = [
              `${image_name}:${major}`,
              `${image_name}:${major}.${minor}`,
              `${image_name}:${major}.${minor}.${patch}`,
            ]
            const tags = []
            if (base_image === 'alpine3.22') {
              tags.push(...version_tags.map(tag => `${tag}-alpine`))
              tags.push(...version_tags.map(tag => `${tag}-alpine3.22`))
              tags.push(`${image_name}:alpine`, `${image_name}:alpine3.22`)
              core.exportVariable('DOCKERFILE_NAME', 'docker/Dockerfile.alpine')
            } else if (base_image === 'trixie') {
              tags.push(...version_tags.map(tag => `${tag}-${base_image}`))
              tags.push(...version_tags)
              tags.push(`${image_name}:${base_image}`, `${image_name}:latest`)
              core.exportVariable('DOCKERFILE_NAME', `docker/Dockerfile.${base_image}`)
            } else if (base_image === 'bookworm') {
              tags.push(...version_tags.map(tag => `${tag}-${base_image}`))
              tags.push(`${image_name}:${base_image}`)
              core.exportVariable('DOCKERFILE_NAME', `docker/Dockerfile.${base_image}`)
            } else {
              process.exit(1)
            }
            core.exportVariable('IMAGE_TAGS', tags.join(','))

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to DockerHub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build without push
        if: github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ${{ env.DOCKERFILE_NAME }}
          platforms: linux/amd64,linux/arm64/v8
          push: false
          tags: ${{ env.IMAGE_TAGS }}

      - name: Build and push
        if: github.event_name == 'push'
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ${{ env.DOCKERFILE_NAME }}
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ env.IMAGE_TAGS }}
