name: Releases

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Release
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ steps.release_drafter.outputs.id }},
              tag_name: '${{ github.ref_name }}',
              name: 'Release ${{ github.ref_name }}',
              draft: context.eventName != 'push'
            });

  docker:
    name: Build Docker Image
    strategy:
      matrix:
        base-image: [alpine3.17, bookworm, bullseye, buster]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up tags
        uses: actions/github-script@v6
        env:
          IMAGE_NAME: harryzcy/nodop
          BASE_IMAGE: ${{ matrix.base-image }}
        with:
          script: |
            const image_name = process.env.IMAGE_NAME
            const tag_name = context.eventName == 'push' ? process.env.GITHUB_REF_NAME : 'v0.0.0'
            const base_image = process.env.BASE_IMAGE
            const [major, minor, patch] = tag_name.slice(1).split('.')
            const version_tags = [
              `${image_name}:${major}`,
              `${image_name}:${major}.${minor}`,
              `${image_name}:${major}.${minor}.${patch}`,
            ]
            const tags = []
            if (base_image === 'alpine3.17') {
              tags.push(...version_tags.map(tag => `${tag}-alpine`))
              tags.push(...version_tags.map(tag => `${tag}-alpine3.17`))
              tags.push(`${image_name}:alpine`, `${image_name}:alpine3.17`)
              core.exportVariable('DOCKERFILE_NAME', 'docker/Dockerfile.alpine')
            } else if (base_image === 'bullseye') {
              tags.push(...version_tags.map(tag => `${tag}-${base_image}`))
              tags.push(...version_tags)
              tags.push(`${image_name}:${base_image}`, `${image_name}:latest`)
              core.exportVariable('DOCKERFILE_NAME', `docker/Dockerfile.${base_image}`)
            } else if (base_image === 'buster') {
              tags.push(...version_tags.map(tag => `${tag}-${base_image}`))
              tags.push(`${image_name}:${base_image}`)
              core.exportVariable('DOCKERFILE_NAME', `docker/Dockerfile.${base_image}`)
            } else {
              process.exit(1)
            }
            core.exportVariable('IMAGE_TAGS', tags.join(','))

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build without push
        if: github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_NAME }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: false
          tags: ${{ env.IMAGE_TAGS }}

      - name: Build and push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_NAME }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.IMAGE_TAGS }}
